### ISSUE TITLE
`combination` `sequential` and `substitutes` operators on drug collections

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/civic-docs#117]
The CIViC documentation lacks clear definitions of what the drug interaction types (`combination`, `sequential`, and `substitutes`) mean and when it is appropriate to use one over another.

Starting the discussion here.

**Comment by arpaddanos** [comment]
My understanding is 

- combination == A and B at the same time
- sequential == First A and then B without overlap
- substitutes == A or B could be used. 

An example of substitutes could be in civic:AID5 (attempt at a Curie notation there). It talks about the approval for the first generation TKIs erlotinib and gefitinib. They can be used interchangeably, one or the other in EGFR mutation NSCLC

**Comment by arpaddanos** [comment]
The documentation should be updated once there is consensus and other more detailed questions from @ahwagner are resolved

**Comment by ahwagner** [comment]
@arpaddanos your definitions mirror my understanding. Beyond this, though, is the need for formal definitions and guidance on when the use of each. The motivation for this comes from the modeling I am doing for MetaKB, where I have created three distinct `TherapeuticCollection` subclasses:

```
  CombinationTherapeutic:
    inherits: TherapeuticCollection
    description: >-
      A set of therapeutics that are taken together as a treatment.

  SequentialTherapeutic:
    inherits: TherapeuticCollection
    description: >-
      A list of therapeutics that are taken sequentially as a treatment.

  SubstitutionTherapeutic:
    inherits: TherapeuticCollection
    description: >-
      A set of therapeutics that are considered valid alternative treatments.
```

**NOTE:** I use Therapeutic here instead of Drug as the term encompasses concepts such as [Radiation Therapy](https://civicdb.org/drugs/360/summary); but the principle of these classes is meant to reflect the "drugs + interaction type" concept from CIViC.

One of the challenges I have with this structure is the notion of `SequentialTherapeutic`. Is the order meaningful in the CIViC data model? In general? More concretely, if a study describes the role of Drug A then Drug B, and another study describes the role of Drug B then Drug A, is it important to the interpretation of the variant to distinguish those statements computationally? Or is the goal simply to index the collection of therapeutics _associated with_ some sequential application of those therapeutics (a regimen)?
